### ISSUE TITLE
TaskStats breakdown can result in "IllegalArgumentException: Comparison method violates its general contract!"

### ISSUE THREAD

**Issue by dweiss** [carrotsearch/progresso#14]
Happened on a CI. 
```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeLo(TimSort.java:781) ~[?:?]
	at java.util.TimSort.mergeAt(TimSort.java:518) ~[?:?]
	at java.util.TimSort.mergeCollapse(TimSort.java:448) ~[?:?]
	at java.util.TimSort.sort(TimSort.java:245) ~[?:?]
	at java.util.Arrays.sort(Arrays.java:1516) ~[?:?]
	at java.util.ArrayList.sort(ArrayList.java:1749) ~[?:?]
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:392) ~[?:?]
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.carrotsearch.progresso.TaskStats.breakdown(TaskStats.java:113) ~[progresso-1.7.0.jar:?]
	at com.carrotsearch.progresso.TaskStats.breakdown(TaskStats.java:98) ~[progresso-1.7.0.jar:?]
	at com.carrotsearch.progresso.TaskStats.breakdown(TaskStats.java:76) ~[progresso-1.7.0.jar:?]
```

Could be that still open tasks cause this? Make it more resilient by snapshotting tasks prior to sorting.

**Comment by dweiss** [comment]
This can happen when calling breakdown on a set of active tasks (not closed).

**Comment by dweiss** [comment]
1. Switch startTime to nanotime.
2. Use a sort-time-consistent snapshot of tasks to avoid race conditions.
